### ISSUE TITLE
Allow: Middleware clearing on group

### ISSUE THREAD

**Issue by paganotoni** [leapkit/core#15]
It would be good to provide a way to clear the Middleware list when using a group. 

```go
s.Use(HTMLRendererMW)

s.Group("/api", func(r *server.Router){
  r.ClearMiddleware()
  
  r.HandleFunc("/admins", adminsListHandler)
})
```

**Comment by tatang26** [comment]
@paganotoni I agree with this idea; I can send something for it.

**Comment by paganotoni** [comment]
This is merged! Thanks @tatang26
