### ISSUE TITLE
Images don't properly load. 

### ISSUE THREAD

**Issue by EdwinPB** [leapkit/core#18]
Issue: 
- When you create the images folder inside the internal assets folder
- And you use the assetPath helper to resolve the source path from the public assets folder. 
- Then the images are not found.

**Comment by tatang26** [comment]
Hey @EdwinPB How are you loading the assets? and also how are you calling them within the template?

**Comment by EdwinPB** [comment]
In the public.go file we have this:
```
var (
	//go:embed *
	Files embed.FS
)
```
Then in the routes.go we have.
`r.HandleFunc(Assets.HandlerPattern(), Assets.HandlerFn) `

And from the template we use this helper. 
` <img class="h-3" src="<%= assetPath('public/images/previous.svg') %>" alt="previous">`

@tatang26 let me know if that answers your question.

**Comment by tatang26** [comment]
@EdwinPB  I have created a [fix](https://github.com/leapkit/core/pull/19) for this bug

**Comment by paganotoni** [comment]
Thanks @tatang26
